package nas.CommonTypes

typedef UInt32 Retcode;
typedef UInt32 SizeT;

const UInt16 FilePathStringSize = 512;
typedef string<FilePathStringSize> FilePathString;

const UInt16 DataBufferSize = 1024;
typedef string<DataBufferSize> DataBuffer;

const UInt8 UserNameStringSize = 128;
typedef string<UserNameStringSize> UserNameString;

const UInt16 PasswordHashSize = 256;
typedef string<PasswordHashSize> PasswordHashString;
